[package]
name = "demo_api_for_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
